        // <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
    #nullable disable
    using System;
    using System.Collections.Generic;
    using Microsoft.EntityFrameworkCore;

    namespace AppWeb1.Models;

    public partial class DeliveryDBContext : DbContext
    {
        public DeliveryDBContext(DbContextOptions<DeliveryDBContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Cliente> Clientes { get; set; }

        public virtual DbSet<DetallePedido> DetallePedidos { get; set; }

        public virtual DbSet<Pedido> Pedidos { get; set; }

        public DbSet<Usuario> Usuarios { get; set; }

        public virtual DbSet<Producto> Productos { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Cliente>(entity =>
            {
                entity.HasKey(e => e.IdCliente).HasName("PK__Cliente__D5946642D90F9902");

                entity.ToTable("Cliente");

                entity.Property(e => e.Apellido)
                    .HasMaxLength(50)
                    .IsUnicode(false);
                entity.Property(e => e.Domicilio)
                    .HasMaxLength(100)
                    .IsUnicode(false);
                entity.Property(e => e.Nombre)
                    .HasMaxLength(50)
                    .IsUnicode(false);
                entity.Property(e => e.NumTelefono)
                    .HasMaxLength(20)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<DetallePedido>(entity =>
            {
                entity.HasKey(e => e.IdDetalle).HasName("PK__DetalleP__E43646A505C30240");

                entity.ToTable("DetallePedido");

                entity.Property(e => e.PrecioUnitario).HasColumnType("decimal(10, 2)");
                //entity.Property(e => e.Subtotal)
                //.HasComputedColumnSql("([Cantidad]*[PrecioUnitario])", true)
                //.HasColumnType("decimal(21, 2)");
                entity.Ignore(e => e.Subtotal);
                entity.HasOne(d => d.IdProductoNavigation).WithMany(p => p.DetallePedidos)
                    .HasForeignKey(d => d.IdProducto)
                    .HasConstraintName("FK__DetallePe__IdPro__182C9B23");

                entity.HasOne(d => d.NumPedidoNavigation).WithMany(p => p.DetallePedidos)
                    .HasForeignKey(d => d.NumPedido)
                    .HasConstraintName("FK__DetallePe__NumPe__173876EA");
            });

            modelBuilder.Entity<Pedido>(entity =>
            {
                entity.HasKey(e => e.NumPedido).HasName("PK__Pedido__CC16BA141D44ADCF");

                entity.ToTable("Pedido");

                entity.Property(e => e.EstadoPedido)
                    .HasMaxLength(20)
                    .IsUnicode(false);
                entity.Property(e => e.FechaPedido).HasColumnType("datetime");
                entity.Property(e => e.MontoTotal).HasColumnType("decimal(10, 2)");
                entity.Property(e => e.Observaciones).HasColumnType("text");

                entity.HasOne(d => d.IdClienteNavigation).WithMany(p => p.Pedidos)
                    .HasForeignKey(d => d.IdCliente)
                    .HasConstraintName("FK__Pedido__IdClient__145C0A3F");
            });

            modelBuilder.Entity<Producto>(entity =>
            {
                entity.HasKey(e => e.IdProducto).HasName("PK__Producto__09889210FD6A81AE");

                entity.ToTable("Producto");

                entity.Property(e => e.Descripcion).HasColumnType("text");
                entity.Property(e => e.NombreProducto)
                    .HasMaxLength(100)
                    .IsUnicode(false);
                entity.Property(e => e.Precio).HasColumnType("decimal(10, 2)");
            });

        modelBuilder.Entity<Usuario>(entity =>
        {
            entity.HasKey(e => e.Id);

            entity.ToTable("Usuarios");

            entity.Property(e => e.NombreUsuario)
                .HasMaxLength(50)
                .IsRequired()
                .IsUnicode(false);

            entity.Property(e => e.Contraseña)
                .HasMaxLength(100)
                .IsRequired()
                .IsUnicode(false);

            entity.Property(e => e.Rol)
                .HasMaxLength(20)
                .IsRequired()
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }