// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppWeb1.Models;

public partial class Pedido
{
    public int NumPedido { get; set; }

    public int? IdCliente { get; set; }

    public DateTime? FechaPedido { get; set; }

    public string EstadoPedido { get; set; }

    public decimal? MontoTotal { get; set; }

    public string Observaciones { get; set; }

    public virtual ICollection<DetallePedido> DetallePedidos { get; set; } = new List<DetallePedido>();

    public virtual Cliente IdClienteNavigation { get; set; }
}